### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox.io#10]
Users should verify their email accounts when signing up. 

From: `Goobox <no-reply@goobox.io>`
Topic: `Please verify your email address`

`Logo`
 ======================================

Hi `<username>`

We just need to verify your email address before your sign up is complete!

`Verify your email` //button

Happy sharing!
=======================================

**Comment by jkawamoto** [comment]
According to [this document](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-email-verification-message-customization.html), it seems not to be easy to use the user name in verification emails. 

They only have one placeholder: 
> the {####} placeholder, which is replaced with the verification code before the message is sent.

but not for usernames.

**Comment by MeijeSibbel** [comment]
btw, this email is sent to trash automatically on outlook, not on gmail though. I guess once we have like `no-reply@goobox.io` and a topic it won't go to trash anymore. 

![image](https://user-images.githubusercontent.com/11735738/44116953-cf3539ba-a009-11e8-8483-362af0ed8175.png)

`Verify your email 359619` should be something like: `verification token: 359619`, i think if we add a link with the token we can automatically activate the user without the requirement for them copy-pasting it. Some UX improvement.

Hmm, maybe we should look around for other email verification providers. btw, can we do this ourselves?, do we have to setup a email server?

**Comment by jkawamoto** [comment]
There is an option to send a verification URL instead if a code. We can try it out but we need to update our authentication code. After finish implementing other functions, I’ll work on that.

We need to set up an email server and proof no-reply@goobox.io exists before using the address.

**Comment by MeijeSibbel** [comment]
https://www.mailgun.com is also a good option.

**Comment by jkawamoto** [comment]
I'll try mailgun to forward emails.

**Comment by MeijeSibbel** [comment]
[email_verification.zip](https://github.com/GooBox/goobox.io/files/2390292/email_verification.zip)
