### ISSUE TITLE
Website content in the wrong place after registering and entering activation code

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox.io#5]
![image](https://user-images.githubusercontent.com/11735738/42532627-c1909e32-8487-11e8-90fe-072d90d54a45.png)

**Comment by jkawamoto** [comment]
I don't reproduce this so far. Could you disable cache and try it again?

**Comment by MeijeSibbel** [comment]
Same thing when removing the cache. Could you please remove my two accounts again so that i can try it in another browser?, thanks.

**Comment by jkawamoto** [comment]
Two accounts are deleted.

**Comment by jkawamoto** [comment]
Does this still happen?

**Comment by MeijeSibbel** [comment]
Not as far as i am aware of, i haven't noticed it recently. Lets close it for now and reopen if it appears again.
