### ISSUE TITLE
Return incompatibility message if user uses a incompatible browser

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox.io#9]
Users visiting the website with a incompatible browser should be notified that they are using a incompatible browser. Furthermore the message should ask the user to switch to one of the supported browsers like chrome. e.g.

`Sorry your browser is not supported, please use ..., ... or ....`

**Comment by jkawamoto** [comment]
This library detects users’ browser types: https://github.com/DamonOehlman/detect-browser/blob/master/README.md
